font_family      family="Maple Mono NF" wght=600 features="+cv04 +cv32 +cv33 +zero +calt"
bold_font        family="Maple Mono NF" wght=800 features="+cv04 +cv32 +cv33 +zero +calt"
italic_font      family="Maple Mono NF" wght=600 features="+cv04 +cv32 +cv33 +zero +calt"
bold_italic_font family="Maple Mono NF" wght=800 features="+cv04 +cv32 +cv33 +zero +calt"

font_size 20

disable_ligatures never

# Cursor
cursor_shape block
unfocused_cursor_shape block
cursor_trail 3

# No stupid close confirmation
confirm_os_window_close 0

# Use fish shell
shell /opt/homebrew/bin/fish

# Copy
map ctrl+c    copy_or_interrupt

map ctrl+plus  change_font_size all +1
map ctrl+equal  change_font_size all +1
map ctrl+kp_add  change_font_size all +1
map ctrl+minus       change_font_size all -1
map ctrl+underscore       change_font_size all -1
map ctrl+kp_subtract       change_font_size all -1
map ctrl+0 change_font_size all 0
map ctrl+kp_0 change_font_size all 0

## name: Rosé Pine
## author: mvllow
## license: MIT
## upstream: https://github.com/rose-pine/kitty/blob/main/dist/rose-pine.conf
## blurb: All natural pine, faux fur and a bit of soho vibes for the classy minimalist

foreground               #e0def4
background               #191724
selection_foreground     #e0def4
selection_background     #403d52

cursor                   #524f67
cursor_text_color        #e0def4

url_color                #c4a7e7

active_tab_foreground    #e0def4
active_tab_background    #26233a
inactive_tab_foreground  #6e6a86
inactive_tab_background  #191724

active_border_color      #31748f
inactive_border_color    #403d52

# black
color0   #26233a
color8   #6e6a86

# red
color1   #eb6f92
color9   #eb6f92

# green
color2   #31748f
color10  #31748f

# yellow
color3   #f6c177
color11  #f6c177

# blue
color4   #9ccfd8
color12  #9ccfd8

# magenta
color5   #c4a7e7
color13  #c4a7e7

# cyan
color6   #ebbcba
color14  #ebbcba

# white
color7   #e0def4
color15  #e0def4
