[settings]
animate = true
animation_duration = 0.3
animation_fps = 100.0

focus_follows_mouse = true
mouse_follows_focus = true

hot_reload = true

[settings.layout]
mode = "scrolling"

[settings.layout.scrolling]
column_width_ratio = 1.0
min_column_width_ratio = 1.0
max_column_width_ratio = 1.0

[settings.ui.menu_bar]
enabled = true
show_empty = false
mode = "all"
active_label = "index"
display_style = "label"

[virtual_workspaces]
enabled = true
default_workspace_count = 10
preserve_focus_per_workspace = true

[modifier_combinations]
comb1 = "Alt + Shift"

[keys]
"Alt + H" = { move_focus = "left" }
"Alt + J" = { move_focus = "down" }
"Alt + K" = { move_focus = "up" }
"Alt + L" = { move_focus = "right" }

"comb1 + H" = { move_node = "left" }
"comb1 + J" = { move_node = "down" }
"comb1 + K" = { move_node = "up" }
"comb1 + L" = { move_node = "right" }

"Alt + 1" = { switch_to_workspace = 0 }
"Alt + 2" = { switch_to_workspace = 1 }
"Alt + 3" = { switch_to_workspace = 2 }
"Alt + 4" = { switch_to_workspace = 3 }
"Alt + 5" = { switch_to_workspace = 4 }
"Alt + 6" = { switch_to_workspace = 5 }
"Alt + 7" = { switch_to_workspace = 6 }
"Alt + 8" = { switch_to_workspace = 7 }
"Alt + 9" = { switch_to_workspace = 8 }
"Alt + 0" = { switch_to_workspace = 9 }

"comb1 + 1" = { move_window_to_workspace = 0 }
"comb1 + 2" = { move_window_to_workspace = 1 }
"comb1 + 3" = { move_window_to_workspace = 2 }
"comb1 + 4" = { move_window_to_workspace = 3 }
"comb1 + 5" = { move_window_to_workspace = 4 }
"comb1 + 6" = { move_window_to_workspace = 5 }
"comb1 + 7" = { move_window_to_workspace = 6 }
"comb1 + 8" = { move_window_to_workspace = 7 }
"comb1 + 9" = { move_window_to_workspace = 8 }
"comb1 + 0" = { move_window_to_workspace = 9 }

"Alt + F" = "toggle_fullscreen"
"Alt + Comma" = "toggle_stack"
"Alt + Slash" = "toggle_orientation"
"Alt + T" = "toggle_window_floating"

"Alt + Enter" = { "exec" = ["/bin/bash", "-c", "open -a \"/opt/homebrew/bin/kitty\""] }

"Alt + Ctrl + Q" = "save_and_exit"
